infojuiceapi/urls.py
from django.contrib import admin
from django.urls import path
from infojuiceapi import views


urlpatterns = [
    path('list', views.ExpListView.as_view(), name='list'),
    path('exp/<int:pk>', views.ExperimentView.as_view(), name='experiment'),
    path('doc/<int:pk>', views.DocumentDetailsView.as_view(), name='document'),
]

infojuicegui/urls.py
from django.contrib import admin
from django.urls import path, include
from infojuicegui import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view(), name='index'),
    path('experiment/<int:pk>', views.ExperimentView.as_view(), name='experiment'),
    path('new', views.NewExperimentView.as_view(), name='new-experiment'),
    path('api/', include(('infojuiceapi.urls', 'api'))),
]

infojuicegui/forms.py
# Copyright (c) 2019 Marco Marinello <marco.marinello@school.rainerum.it>
# See LICENSE file
#
# Forms

from django import forms
from django.conf import settings


class NewExperimentForm(forms.Form):
    customers = forms.MultipleChoiceField(
        choices=settings.CUSTOMERS,
        widget=forms.CheckboxSelectMultiple
    )

    features = forms.MultipleChoiceField(
        choices=settings.FEATURES,
        widget=forms.CheckboxSelectMultiple
    )

    classifier = forms.ChoiceField(choices=settings.CLASSIFIERS)

    hyperparameters = forms.ChoiceField(choices=[["no", "please select classifier"]])

    validation_score = forms.ChoiceField(choices=settings.VALIDATION_SCORES)

    content_language = forms.ChoiceField(choices=settings.CONTENT_LANGUAGES)

    content_type = forms.ChoiceField(choices=settings.CONTENT_TYPES)

    content_length = forms.ChoiceField(choices=settings.CONTENT_LENGTH)

infojuiceapi/views.py
# Copyright (c) 2019 Marco Marinello <marco.marinello@school.rainerum.it>
# See LICENSE file
#
# API views

from infojuiceapi.utils import APIQuery


class ExpListView(APIQuery):
    function = "list"


class ExperimentView(APIQuery):
    function = "experiment"


class DocumentDetailsView(APIQuery):
    function = "document"

infojuicegui/views.py
# Copyright (c) 2019 Marco Marinello <marco.marinello@school.rainerum.it>
# See LICENSE file
#
# Main django views


from django.views.generic import TemplateView
from django.utils.translation import ugettext_lazy as _
from django.conf import settings
from django.views.generic.edit import FormView
from . import forms


class IndexView(TemplateView):
    template_name = "index.html"


class ExperimentView(TemplateView):
    template_name = "experiment.html"
    header_fields = [
        # field name, field id
        [_("Source language"), "source_language"],
        [_("Content length"), "content_length"],
        [_("Content type"), "content_type"],
        [_("Classifier"), "classifier"],
        [_("Balancing"), "balancing"],
        [_("Validation score"), "validation_score"],
        [_("Hyperparameter values"), "hyperparameter_values"],
    ]

    def get_context_data(self, pk):
        orig = super().get_context_data(pk=pk)
        orig["hdfields"] = self.header_fields
        return orig


class NewExperimentView(FormView):
    form_class = forms.NewExperimentForm
    template_name = "newexperiment.html"

    def get_context_data(self, **kw):
        ctx = super().get_context_data(**kw)
        ctx["HYPERPARAMETERS"] = settings.HYPERPARAMETERS
        return ctx

infojuicegui/templates/base.html
{% load i18n static %}
<!DOCTYPE html>
<html lang="it">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="copyright" content="Marco Marinello">

    <link rel="stylesheet" href="{% static 'bootstrap4/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesome5/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'datatables1/datatables.min.css' %}">

    <script src="{% static 'jquery3/jquery.min.js' %}"></script>
    <script src="{% static 'popperjs1/umd/popper.min.js' %}"></script>
    <script src="{% static 'bootstrap4/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'datatables1/datatables.min.js' %}"></script>
    <script src="{% static 'flot0/jquery.flot.js' %}"></script>

    <title>{% block title %}Base template{% endblock %} - InfoJuice</title>
  </head>
  <body>
    {% block standardcontent %}
    <div class="container">
      <div class="jumbotron">
        {% for message in messages %}
        <div class="alert alert-{{message.tags}}">
          {{message}}
        </div>
        {% endfor %}
        {% block content %}
        {% endblock content %}
      </div>
    </div>
    {% endblock standardcontent %}
  </body>
</html>

infojuicegui/templates/detailsmodal.html
{% load i18n %}

<script type="text/javascript">

function displayDetails(docid) {
  console.log(docid);
  $("#docdetails").modal();
  var url = "{% url 'api:document' pk=0 %}";
  url = url.substring(0, url.length-1);
  url += docid.toString();
  $.ajax({
    url: url,
    dataType: "json"
  }).done(function (data) {
    console.log(data);
    for (k in data) {
      $("#dd_"+k).text(data[k]);
    }
  });
}

</script>

<div class="modal" id="docdetails" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">#<a id="dd_id"></a>: <a id="dd_title"></a></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <b>{% trans "Date" %}</b>: <a id="dd_date"></a><br>
        <b>{% trans "Subtitle" %}</b>: <a id="dd_subtitle"></a><br>
        <b>{% trans "Subhead" %}</b>: <a id="dd_subhead"></a><br>
        <b>{% trans "Type" %}</b>: <a id="dd_type"></a><br>
        <b>{% trans "Source id" %}</b>: <a id="dd_source_id"></a><br>
        <b>{% trans "Source language" %}</b>: <a id="dd_source_language"></a><br>
        <b>{% trans "Page" %}</b>: <a id="dd_page"></a><br>
        <b>{% trans "Headlines" %}</b>: <a id="dd_headlines"></a><br>
        <b>{% trans "Text" %}</b>: <textarea id="dd_text" style="min-width:80%; height:100px;"></textarea>
      </div>
    </div>
  </div>
</div>

infojuicegui/templates/experiment.html
{% extends "base.html" %}{% load i18n %}
{% block title %}{% trans "Experiment details" %}{% endblock %}

{% block content %}
<h1><a class="btn btn-lg btn-secondary" href="{% url 'index' %}"><i class="fas fa-arrow-left"></i></a> <i id="pk">#{{pk}}</i> {% trans "Experiment details" %}</h1>

<br>

<div class="row">
  {% for f in hdfields %}
  <div class="col-lg-{% if f.1 == 'hyperparameter_values'%}6{% else %}4{% endif %}"><b>{% trans f.0 %}:</b> <a id="{{f.1}}"></a></div>
  {% endfor %}
</div>

<div class="row">
  <div class="col-lg-1 text-right"><b>{% trans "Features" %}:</b></div>
  <div class="col-lg-2" id="features"></div>
  <div class="col-lg-1"></div>
  <div class="col-lg-1 text-right"><b>{% trans "Customers" %}:</b></div>
  <div class="col-lg-2"><a id="customers"></a></div>
</div>

<br><br>

<h2><b>{% trans "Results" %}</b></h2>

<table class="table table-striped" id="period_results">
  <thead>
    <tr>
      <th>{% trans "Period" %}</th>
      <th>{% trans "Precision" %}</th>
      <th>{% trans "Recall" %}</th>
      <th>{% trans "F1 score" %}</th>
      <th></th>
    </tr>
  </thead>
</table>

<br><br>

<div id="period_details" style="display: none;">
  <h2><b>{% trans "Period details" %}: <a id="period_name"></a></b></h2>
  <br>
  <div class="row">
    <div class="col-lg-4"><b>{% trans "Precision" %}:</b> <a id="period_precision"></a></div>
    <div class="col-lg-4"><b>{% trans "Recall" %}:</b> <a id="period_recall"></a></div>
    <div class="col-lg-4"><b>{% trans "F1 score" %}:</b> <a id="period_f1score"></a></div>
  </div>

  <div class="row">
    <div class="col-lg-6">
      <br><b>{% trans "Filter date" %}:</b> <input type="date" id="date-filter" />
      <a href="#period_details" id="period_filter" class="btn btn-lg btn-warning">
        <i class="fas fa-sync" aria-hidden="true"></i>
        {% trans "Update" %}
      </a>
      <a href="#period_details" id="period_delete" class="btn btn-lg btn-success">
        <i class="fas fa-times" aria-hidden="true"></i>
        {% trans "Clear filters" %}
      </a>
    </div>
    <div class="col-lg-6" style="vertical-align: middle;">
      <br>
      {% trans "Threshold" %}: <input type="text" id="period_threshold" />
    </div>
  </div>
  <br>
  <br>

  <table class="table table-striped" id="period_detail_table">
    <thead>
      <tr>
        <th>#</th>
        <th>{% trans "Title" %}</th>
        <th>{% trans "Date" %}</th>
        <th>{% trans "Text" %}</th>
        <th>{% trans "Editor choice" %}</th>
        <th>{% trans "Score" %}</th>
        <th></th>
      </tr>
    </thead>
  </table>

  <br><br>

  <div style="height:250px; width:100%;" id="period_plot"></div>

</div>


<script type="text/javascript">

  $.ajax({
    url: "{% url 'api:experiment' pk=pk %}",
    dataType: "json"
  }).done(function(data) {
    console.log("header fill");
    var hdfill = [
      {% for f in hdfields %}"{{f.1}}",
      {% endfor %}
    ];
    for (field in hdfill) {
      var o = hdfill[field];
      if (typeof(data[o]) == "object") {
        var texted = "";
        for (k in data[o]) {
          texted += k + ": " + data[o][k];
        }
        $("#"+o).text(texted);
      }
      else $("#"+o).text(data[o]);
    }

    console.log("features fill");
    for (f in data["features"]) {
      var feature = data["features"][f];
      $("#features").append("<i class='fas fa-check-square'></i> "+feature+"<br>");
    }

    console.log("customers fill");
    for (f in data["customers"]) {
      var customer = data["customers"][f];
      $("#customers").append("<input type='radio' name='customers' onclick='fill_from_customer(\""+customer+"\");'> "+customer+"<br>");
    }

    document.period_detail_table = $("#period_detail_table").DataTable();
    document.period_results_table = $("#period_results").DataTable();
    document.data = data;
  });


  function fill_from_customer(cust) {
    var data = document.data;
    console.log("results months fill");
    var for_dt = [];
    for (period in data["results"][cust]) {
      var th = [period];
      th.push(data["results"][cust][period]["precision"]);
      th.push(data["results"][cust][period]["recall"]);
      th.push(data["results"][cust][period]["f1_score"]);
      th.push("<a class='btn btn-lg btn-primary fas fa-eye' href='#period_details' onclick='period_details(\""+period+"\");'></a>");
      for_dt.push(th);
    }
    document.period_results_table.clear();
    document.period_results_table.rows.add(for_dt);
    document.period_results_table.draw();
    document.cust = cust;
  }


  function period_details(period) {
    console.log("show period " + period + " details");
    $("#period_name").text(period);
    var docs = document.data["results"][document.cust][period]["scores"];
    console.log(docs);""
    var for_dt = [];
    for (doc in docs) {
      var line = docs[doc];
      console.log(line);
      var tr = [];
      tr.push(line["content_id"]);
      tr.push(line["title"]);
      var thisdate = new Date(line["timestamp"]*1000);
      tr.push(thisdate.toISOString().split('T')[0]);
      tr.push(line["text_preview"]);
      tr.push(line["editor_choice"]);
      tr.push(line["score"]);
      tr.push("<a href='#' class='btn btn-lg btn-primary fas fa-eye' onclick='displayDetails("+line["content_id"]+")'></a>");
      for_dt.push(tr);
    }
    document.period_detail_table.clear();
    document.period_detail_table.rows.add(for_dt);
    document.period_detail_table.draw();
    document.viewing_period = for_dt;
    $("#period_details").slideDown();
    compute_period(for_dt);
  }


  function commonvars(data, threshold) {
    var truepositive = 0,
        truenegative = 0,
        falsepositive = 0,
        falsenegative = 0;
    for (line in data) {
      var row = data[line];
      var score = row[5],
          editor = row[4];
      if (score >= threshold && editor == 1) truepositive += 1;
      else if (score < threshold && editor == 0) truenegative += 1;
      else if (score >= threshold && editor == 0) falsepositive += 1;
      else if (score < threshold && editor == 1) falsenegative += 1;
    }
    var precision = truepositive/(truepositive+falsepositive),
        recall = truepositive/(truepositive+falsenegative)
        f1score = 2*(precision*recall)/(precision+recall);
    return [
      truepositive,
      truenegative,
      falsepositive,
      falsenegative,
      threshold,
      precision,
      recall,
      f1score
    ]
  }


  function compute_period(data) {
    // find TP, TN, FP and FN
    var result = commonvars(data, parseFloat($("#period_threshold").val()));
    $("#period_precision").text(result[5]);
    $("#period_recall").text(result[6]);
    $("#period_f1score").text(result[7]);
    // distinct all values of the score
    var scores = [];
    for (line in data) {
      var row = data[line];
      var score = row[5];
      if (!scores.includes(score)) scores.push(score);
    }
    // loop over all scores and plot different dots
    var dots = [];
    document.dots_with_threshold = {}
    for (x in scores) {
      var threshold = scores[x];
      var result = commonvars(data, threshold);
      dots.push([result[5], result[6]]);
      document.dots_with_threshold[threshold] = [result[5], result[6]];
    }
    // plot
    $.plot("#period_plot", [dots], {
      "xaxis": {
        "min": 0,
        "max": 1
      },
      "yaxis": {
        "min": 0,
        "max": 1
      },
      "series": {
        "lines": {"show": true},
        "points": {"show": true}
      },
      "pan": {
        "interactive": true,
        "enableTouch": true
      },
      "grid": {
        "hoverable": true,
        "clickable": true
      }
    });
  }


  $("#period_plot").bind("plotclick", function (event, pos, item) {
    var threshold;
    for (v in document.dots_with_threshold) {
      var dot = document.dots_with_threshold[v];
      if (dot[0] == item.datapoint[0] && dot[1] == item.datapoint[1]) threshold=v;
    }
    if (threshold) {
      alert("Precision: " + item.datapoint[0] + " Recall: " + item.datapoint[1] + " Threshold: " + threshold);
    }
  });


  $("#period_filter").click(function () {
    var date = $("#date-filter").val();
    // now reload all the data and filter it
    var filtered_dt = [];
    for (x in document.viewing_period) {
      var line = document.viewing_period[x];
      var thisdate = line[2];
      if (thisdate == date) filtered_dt.push(line);
    }
    document.period_detail_table.clear();
    document.period_detail_table.rows.add(filtered_dt);
    document.period_detail_table.draw();
    compute_period(filtered_dt);
  });


  $("#period_threshold").on('change textInput input', function() {
    console.log("Threshold changed, recomputing period stats");
    compute_period(document.period_detail_table.rows().data());
  });


  $("#period_delete").click(function () {
    document.period_detail_table.clear();
    document.period_detail_table.rows.add(document.viewing_period);
    document.period_detail_table.draw();
    compute_period(document.viewing_period);
  });

</script>

{% include 'detailsmodal.html' %}

{% endblock %}

infojuicegui/templates/index.html
{% extends "base.html" %}{% load i18n %}
{% block title %}{% trans "Experiments list" %}{% endblock %}

{% block content %}
<div class="row">
  <div class="col-lg-6"><h1>{% trans "Experiments list" %}</h1></div>
  <div class="col-lg-6 text-right"><a href="{% url 'new-experiment' %}" class="btn btn-lg btn-success"><i class="fas fa-plus"></i></a></div>
</div>

<br>

<table class="table table-striped" id="tb">
  <thead>
    <tr>
      <th>{% trans "#" %}</th>
      <th>{% trans "Experiment name" %}</th>
      <th><i class="fas fa-info" aria-hidden="true"></i></th>
    </tr>
  </thead>
</table>


<script type="text/javascript">
  $("#tb").DataTable({
    "ajax": "{% url 'api:list' %}"
  });
</script>


{% endblock %}

infojuicegui/templates/newexperiment.html
{% extends "base.html" %}{% load i18n %}
{% block title %}{% trans "Launch new experiment" %}{% endblock %}

{% block content %}
<h1>{% trans "Launch new experiment" %}</h1>

{{form.as_p}}


<script type="text/javascript">

document.HYPERPARAMETERS = {{HYPERPARAMETERS|safe}};


function load_hyperparameters() {
  var current = $("#id_classifier").val();
  $("#id_hyperparameters").html("");
  for (k in document.HYPERPARAMETERS[current]) {
    line = document.HYPERPARAMETERS[current][k];
    $("#id_hyperparameters").append("<option value='"+line[0]+"'>"+line[1]+"</option>");
  }
}


$("#id_classifier").change(load_hyperparameters);

$(document).ready(load_hyperparameters);

</script>

{% endblock %}